# Generated by Django 5.1.1 on 2025-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_semsiter_even_odd'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semister',
            field=models.CharField(blank=True, choices=[('1st', 'First Semister'), ('2nd', 'Second Semister'), ('3rd', 'Third Semister'), ('4th', 'Fourth Semister'), ('5th', 'Fifth Semister'), ('6th', 'Sixth Semister')], max_length=20, null=True),
        ),
    ]
