# Generated by Django 5.1.1 on 2025-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_semister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semister',
            field=models.CharField(blank=True, choices=[('first-semester', 'first-semester'), ('second-semester', 'second-semester'), ('third-semester', 'third-semester'), ('fourth-semester', 'fourth-semester'), ('fifth-semester', 'fifth-semester'), ('sixth-semester', 'sixth-semester'), ('seventh-semester', 'seventh-semester')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='semsiter_even_odd',
            name='even_odd',
            field=models.CharField(blank=True, choices=[('Even', 'Even'), ('Odd', 'Odd')], max_length=10, null=True),
        ),
    ]
