# Generated by Django 5.1.1 on 2025-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course_discount_course_discounted_price_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
    ]
