# Generated by Django 5.1.1 on 2025-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_website_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
