# Generated by Django 5.1.1 on 2025-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_courseenrollment_is_active_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_video',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
