# Generated by Django 5.1.1 on 2025-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_class_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
